# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-17 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secutec_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='agente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
