# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-17 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secutec_login', '0002_cliente_agente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAgente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=45, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
